
  CREATE TABLE "PROJECTMAN"."ACCOUNTS" 
   (	"ACCOUNTID" NUMBER, 
	"USERNAME" VARCHAR2(100) NOT NULL ENABLE, 
	"PASSWORDHASH" VARCHAR2(255) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(255) NOT NULL ENABLE, 
	"ROLE" VARCHAR2(50) NOT NULL ENABLE, 
	"EMPLOYEEID" NUMBER, 
	 CHECK (Role IN ('Admin', 'Employee', 'Manager')) ENABLE, 
	 PRIMARY KEY ("ACCOUNTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_ACCOUNTEMPLOYEE" FOREIGN KEY ("EMPLOYEEID")
	  REFERENCES "PROJECTMAN"."EMPLOYEES" ("EMPLOYEEID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"

  CREATE TABLE "PROJECTMAN"."EMPLOYEES" 
   (	"EMPLOYEEID" NUMBER, 
	"EMPLOYEENAME" VARCHAR2(255) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(255) NOT NULL ENABLE, 
	"DEPARTMENT" VARCHAR2(100), 
	"JOBTITLE" VARCHAR2(100), 
	"IMAGE" VARCHAR2(255), 
	 PRIMARY KEY ("EMPLOYEEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"

  CREATE TABLE "PROJECTMAN"."PROJECTS" 
   (	"PROJECTID" NUMBER, 
	"PROJECTNAME" VARCHAR2(255) NOT NULL ENABLE, 
	"STARTDATE" DATE NOT NULL ENABLE, 
	"ENDDATE" DATE, 
	"STATUS" VARCHAR2(50) NOT NULL ENABLE, 
	"PROJECTMANAGERID" NUMBER, 
	 CHECK (Status IN ('Not Started', 'In Progress', 'Completed', 'On Hold')) ENABLE, 
	 PRIMARY KEY ("PROJECTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_PROJECTMANAGER" FOREIGN KEY ("PROJECTMANAGERID")
	  REFERENCES "PROJECTMAN"."EMPLOYEES" ("EMPLOYEEID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"

  CREATE TABLE "PROJECTMAN"."TASKASSIGNMENTS" 
   (	"ASSIGNMENTID" NUMBER, 
	"TASKID" NUMBER NOT NULL ENABLE, 
	"EMPLOYEEID" NUMBER NOT NULL ENABLE, 
	"ASSIGNEDDATE" DATE DEFAULT SYSDATE, 
	"STATUS" VARCHAR2(50) NOT NULL ENABLE, 
	 CHECK (Status IN ('Pending', 'Accepted', 'Rejected', 'Completed')) ENABLE, 
	 PRIMARY KEY ("ASSIGNMENTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_ASSIGNMENTTASK" FOREIGN KEY ("TASKID")
	  REFERENCES "PROJECTMAN"."TASKS" ("TASKID") ENABLE, 
	 CONSTRAINT "FK_ASSIGNMENTEMPLOYEE" FOREIGN KEY ("EMPLOYEEID")
	  REFERENCES "PROJECTMAN"."EMPLOYEES" ("EMPLOYEEID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"

  CREATE TABLE "PROJECTMAN"."TASKS" 
   (	"TASKID" NUMBER, 
	"TASKNAME" VARCHAR2(255) NOT NULL ENABLE, 
	"TASKDESCRIPTION" CLOB, 
	"PROJECTID" NUMBER NOT NULL ENABLE, 
	"ASSIGNEEID" NUMBER, 
	"STATUS" VARCHAR2(50) NOT NULL ENABLE, 
	"STARTDATE" DATE NOT NULL ENABLE, 
	"ENDDATE" DATE, 
	 CHECK (Status IN ('Not Started', 'In Progress', 'Completed', 'On Hold')) ENABLE, 
	 PRIMARY KEY ("TASKID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_TASKPROJECT" FOREIGN KEY ("PROJECTID")
	  REFERENCES "PROJECTMAN"."PROJECTS" ("PROJECTID") ENABLE, 
	 CONSTRAINT "FK_TASKASSIGNEE" FOREIGN KEY ("ASSIGNEEID")
	  REFERENCES "PROJECTMAN"."EMPLOYEES" ("EMPLOYEEID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("TASKDESCRIPTION") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT))
REM INSERTING into PROJECTMAN.ACCOUNTS
SET DEFINE OFF;
REM INSERTING into PROJECTMAN.EMPLOYEES
SET DEFINE OFF;
REM INSERTING into PROJECTMAN.PROJECTS
SET DEFINE OFF;
REM INSERTING into PROJECTMAN.TASKASSIGNMENTS
SET DEFINE OFF;
REM INSERTING into PROJECTMAN.TASKS
SET DEFINE OFF;

  CREATE UNIQUE INDEX "PROJECTMAN"."SYS_C007159" ON "PROJECTMAN"."EMPLOYEES" ("EMPLOYEEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"

  CREATE UNIQUE INDEX "PROJECTMAN"."SYS_C007160" ON "PROJECTMAN"."EMPLOYEES" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"

  CREATE UNIQUE INDEX "PROJECTMAN"."SYS_C007166" ON "PROJECTMAN"."ACCOUNTS" ("ACCOUNTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"

  CREATE UNIQUE INDEX "PROJECTMAN"."SYS_C007167" ON "PROJECTMAN"."ACCOUNTS" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"

  CREATE UNIQUE INDEX "PROJECTMAN"."SYS_C007168" ON "PROJECTMAN"."ACCOUNTS" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"

  CREATE UNIQUE INDEX "PROJECTMAN"."SYS_C007174" ON "PROJECTMAN"."PROJECTS" ("PROJECTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"

  CREATE UNIQUE INDEX "PROJECTMAN"."SYS_C007181" ON "PROJECTMAN"."TASKS" ("TASKID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"

  CREATE UNIQUE INDEX "PROJECTMAN"."SYS_C007188" ON "PROJECTMAN"."TASKASSIGNMENTS" ("ASSIGNMENTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"


  CREATE UNIQUE INDEX "PROJECTMAN"."SYS_C007166" ON "PROJECTMAN"."ACCOUNTS" ("ACCOUNTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"

  CREATE UNIQUE INDEX "PROJECTMAN"."SYS_C007167" ON "PROJECTMAN"."ACCOUNTS" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"

  CREATE UNIQUE INDEX "PROJECTMAN"."SYS_C007168" ON "PROJECTMAN"."ACCOUNTS" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"

  CREATE UNIQUE INDEX "PROJECTMAN"."SYS_C007159" ON "PROJECTMAN"."EMPLOYEES" ("EMPLOYEEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"

  CREATE UNIQUE INDEX "PROJECTMAN"."SYS_C007160" ON "PROJECTMAN"."EMPLOYEES" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"

  CREATE UNIQUE INDEX "PROJECTMAN"."SYS_C007174" ON "PROJECTMAN"."PROJECTS" ("PROJECTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"


  CREATE UNIQUE INDEX "PROJECTMAN"."SYS_C007188" ON "PROJECTMAN"."TASKASSIGNMENTS" ("ASSIGNMENTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"

  CREATE UNIQUE INDEX "PROJECTMAN"."SYS_C007181" ON "PROJECTMAN"."TASKS" ("TASKID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"

  ALTER TABLE "PROJECTMAN"."ACCOUNTS" ADD UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "PROJECTMAN"."ACCOUNTS" ADD UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "PROJECTMAN"."ACCOUNTS" ADD PRIMARY KEY ("ACCOUNTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "PROJECTMAN"."ACCOUNTS" ADD CHECK (Role IN ('Admin', 'Employee', 'Manager')) ENABLE
  ALTER TABLE "PROJECTMAN"."ACCOUNTS" MODIFY ("ROLE" NOT NULL ENABLE)
  ALTER TABLE "PROJECTMAN"."ACCOUNTS" MODIFY ("EMAIL" NOT NULL ENABLE)
  ALTER TABLE "PROJECTMAN"."ACCOUNTS" MODIFY ("PASSWORDHASH" NOT NULL ENABLE)
  ALTER TABLE "PROJECTMAN"."ACCOUNTS" MODIFY ("USERNAME" NOT NULL ENABLE)

  ALTER TABLE "PROJECTMAN"."EMPLOYEES" ADD UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "PROJECTMAN"."EMPLOYEES" ADD PRIMARY KEY ("EMPLOYEEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "PROJECTMAN"."EMPLOYEES" MODIFY ("EMAIL" NOT NULL ENABLE)
  ALTER TABLE "PROJECTMAN"."EMPLOYEES" MODIFY ("EMPLOYEENAME" NOT NULL ENABLE)

  ALTER TABLE "PROJECTMAN"."PROJECTS" ADD PRIMARY KEY ("PROJECTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "PROJECTMAN"."PROJECTS" ADD CHECK (Status IN ('Not Started', 'In Progress', 'Completed', 'On Hold')) ENABLE
  ALTER TABLE "PROJECTMAN"."PROJECTS" MODIFY ("STATUS" NOT NULL ENABLE)
  ALTER TABLE "PROJECTMAN"."PROJECTS" MODIFY ("STARTDATE" NOT NULL ENABLE)
  ALTER TABLE "PROJECTMAN"."PROJECTS" MODIFY ("PROJECTNAME" NOT NULL ENABLE)

  ALTER TABLE "PROJECTMAN"."TASKASSIGNMENTS" ADD PRIMARY KEY ("ASSIGNMENTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "PROJECTMAN"."TASKASSIGNMENTS" ADD CHECK (Status IN ('Pending', 'Accepted', 'Rejected', 'Completed')) ENABLE
  ALTER TABLE "PROJECTMAN"."TASKASSIGNMENTS" MODIFY ("STATUS" NOT NULL ENABLE)
  ALTER TABLE "PROJECTMAN"."TASKASSIGNMENTS" MODIFY ("EMPLOYEEID" NOT NULL ENABLE)
  ALTER TABLE "PROJECTMAN"."TASKASSIGNMENTS" MODIFY ("TASKID" NOT NULL ENABLE)

  ALTER TABLE "PROJECTMAN"."TASKS" ADD PRIMARY KEY ("TASKID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "PROJECTMAN"."TASKS" ADD CHECK (Status IN ('Not Started', 'In Progress', 'Completed', 'On Hold')) ENABLE
  ALTER TABLE "PROJECTMAN"."TASKS" MODIFY ("STARTDATE" NOT NULL ENABLE)
  ALTER TABLE "PROJECTMAN"."TASKS" MODIFY ("STATUS" NOT NULL ENABLE)
  ALTER TABLE "PROJECTMAN"."TASKS" MODIFY ("PROJECTID" NOT NULL ENABLE)
  ALTER TABLE "PROJECTMAN"."TASKS" MODIFY ("TASKNAME" NOT NULL ENABLE)

  ALTER TABLE "PROJECTMAN"."ACCOUNTS" ADD CONSTRAINT "FK_ACCOUNTEMPLOYEE" FOREIGN KEY ("EMPLOYEEID")
	  REFERENCES "PROJECTMAN"."EMPLOYEES" ("EMPLOYEEID") ENABLE

  ALTER TABLE "PROJECTMAN"."PROJECTS" ADD CONSTRAINT "FK_PROJECTMANAGER" FOREIGN KEY ("PROJECTMANAGERID")
	  REFERENCES "PROJECTMAN"."EMPLOYEES" ("EMPLOYEEID") ENABLE

  ALTER TABLE "PROJECTMAN"."TASKASSIGNMENTS" ADD CONSTRAINT "FK_ASSIGNMENTEMPLOYEE" FOREIGN KEY ("EMPLOYEEID")
	  REFERENCES "PROJECTMAN"."EMPLOYEES" ("EMPLOYEEID") ENABLE
  ALTER TABLE "PROJECTMAN"."TASKASSIGNMENTS" ADD CONSTRAINT "FK_ASSIGNMENTTASK" FOREIGN KEY ("TASKID")
	  REFERENCES "PROJECTMAN"."TASKS" ("TASKID") ENABLE

  ALTER TABLE "PROJECTMAN"."TASKS" ADD CONSTRAINT "FK_TASKASSIGNEE" FOREIGN KEY ("ASSIGNEEID")
	  REFERENCES "PROJECTMAN"."EMPLOYEES" ("EMPLOYEEID") ENABLE
  ALTER TABLE "PROJECTMAN"."TASKS" ADD CONSTRAINT "FK_TASKPROJECT" FOREIGN KEY ("PROJECTID")
	  REFERENCES "PROJECTMAN"."PROJECTS" ("PROJECTID") ENABLE
